server.name: kibana
server.host: "0"
elasticsearch.url: http://es:9200

xpack.monitoring.ui.container.elasticsearch.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false
